updated schema with updateCourse updateStudent and updateUser
Hack4Impact-UMD/y-knot pull request #26
Opened 2023-03-28 21:18 UTC by ssharm1524

2023-03-28 22:34 UTC, sophtsai commented on react-app/src/backend/FirestoreCalls.ts
> +    birthdate: student.birthDate,
"birthdate" capitalization -> should be "birthDate"

2023-03-28 22:37 UTC, sophtsai commented on react-app/src/backend/FirestoreCalls.ts
> +  return updateDoc(studentRef, {
Add a `.then() .catch()` structure to this as well

2023-03-29 03:47 UTC, sophtsai requested changes

2023-03-29 03:47 UTC, sophtsai commented on react-app/src/backend/FirestoreCalls.ts
>  import { type Teacher, type TeacherCourse } from '../types/UserType';
You can just append the YKNOTUser type in this line

2023-03-29 22:12 UTC, sahilg24 approved these changes
Looks good!

2023-03-29 22:13 UTC, merged